import 'package:flutter/material.dart';
import '../models/reel_item.dart';

/// مستودع ومضات القرآنية والإسلامية
/// 8 فيديوهات قصيرة 720p HD MP4 محملة ومخزنة محلياً بالكامل للتشغيل بدون إنترنت
class ReelsRepository {
  static List<ReelItem> getInitialReels() {
    return const [
      ReelItem(
        id: 'wamda_01',
        title: 'ألا بذكر الله تطمئن القلوب',
        contentSnippet: '﴿أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ﴾',
        category: ReelCategory.quran,
        authorName: 'مشاري راشد العفاسي',
        videoPath: 'assets/wamadat/wamda_01.mp4',
        assetPath: 'assets/wamadat/wamda_01.mp3',
        audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/013028.mp3',
        surahName: 'سورة الرعد',
        surahNumber: 13,
        ayahNumber: 28,
        durationSeconds: 18,
        resolution: '720p HD',
        fileSizeBytes: 734000, // 734 KB فيديو 720p MP4
        initialLikesCount: 1420,
        tags: ['طمأنينة', 'ذكر_الله', 'تلاوة_خاشعة'],
        gradientColors: [Color(0xFF0D324D), Color(0xFF7F5A83)],
        tafsirOrExplanation: 'أي: تسكن إلى ذكر الله، وتأنس به، وترتاح إليه، ويزول عنها الخوف والاضطراب.',
      ),
      ReelItem(
        id: 'wamda_02',
        title: 'وقفة تدبر: فرج الله قريب',
        contentSnippet: '﴿فَإِنَّ مَعَ الْعُسْرِ يُسْرًا ۝ إِنَّ مَعَ الْعُسْرِ يُسْرًا﴾',
        category: ReelCategory.dawah,
        authorName: 'محمود خليل الحصري',
        videoPath: 'assets/wamadat/wamda_02.mp4',
        assetPath: 'assets/wamadat/wamda_02.mp3',
        audioUrl: 'https://everyayah.com/data/Husary_128kbps/094005.mp3',
        surahName: 'سورة الشرح',
        surahNumber: 94,
        ayahNumber: 5,
        durationSeconds: 14,
        resolution: '720p HD',
        fileSizeBytes: 480000, // 480 KB فيديو 720p MP4
        initialLikesCount: 2310,
        tags: ['تفاؤل', 'فرج', 'تدبر_آية'],
        gradientColors: [Color(0xFF1B3D2B), Color(0xFF2C5E3B)],
        tafsirOrExplanation: 'تأكيد بأن كل ضائقة يعقبها تيسير، ولن يغلب عسر يسرين.',
      ),
      ReelItem(
        id: 'wamda_03',
        title: 'خُلق المسلم: الكلمة الطيبة',
        contentSnippet: '﴿وَقُولُوا لِلنَّاسِ حُسْنًا﴾\nجمال اللسان يعكس نقاء الجنان، تلطف في حديثك تبلغ القلوب.',
        category: ReelCategory.awareness,
        authorName: 'محمد صديق المنشاوي',
        videoPath: 'assets/wamadat/wamda_03.mp4',
        assetPath: 'assets/wamadat/wamda_03.mp3',
        audioUrl: 'https://everyayah.com/data/Minshawy_Murattal_128kbps/002083.mp3',
        surahName: 'سورة البقرة',
        surahNumber: 2,
        ayahNumber: 83,
        durationSeconds: 20,
        resolution: '720p HD',
        fileSizeBytes: 867000, // 867 KB فيديو 720p MP4
        initialLikesCount: 980,
        tags: ['أخلاق', 'الكلمة_الطيبة', 'توعية_إسلامية'],
        gradientColors: [Color(0xFF355C7D), Color(0xFF6C5B7B)],
        tafsirOrExplanation: 'أمر إلهي بحسن الخطاب مع سائر الناس، فالخلق الحسن عنوان الإيمان.',
      ),
      ReelItem(
        id: 'wamda_04',
        title: 'دعاء جامع للهم والغم',
        contentSnippet: '﴿لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ﴾\nدعوة ذي النون ما دعا بها مكروب إلا فرّج الله عنه.',
        category: ReelCategory.dua,
        authorName: 'عبد الباسط عبد الصمد',
        videoPath: 'assets/wamadat/wamda_04.mp4',
        assetPath: 'assets/wamadat/wamda_04.mp3',
        audioUrl: 'https://everyayah.com/data/Abdul_Basit_Murattal_192kbps/021087.mp3',
        surahName: 'سورة الأنبياء',
        surahNumber: 21,
        ayahNumber: 87,
        durationSeconds: 20,
        resolution: '720p HD',
        fileSizeBytes: 783000, // 783 KB فيديو 720p MP4
        initialLikesCount: 3120,
        tags: ['أدعية', 'تفريج_الكرب', 'يونس_عليه_السلام'],
        gradientColors: [Color(0xFF2C3E50), Color(0xFF4CA1AF)],
        tafsirOrExplanation: 'توحيد الله وتنزيهه مع الاعتراف بالذنب، وهو سر إجابة هذا الدعاء العظيم.',
      ),
      ReelItem(
        id: 'wamda_05',
        title: 'أعظم آية في كتاب الله - آية الكرسي',
        contentSnippet: '﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ﴾',
        category: ReelCategory.quran,
        authorName: 'مشاري راشد العفاسي',
        videoPath: 'assets/wamadat/wamda_05.mp4',
        assetPath: 'assets/wamadat/wamda_05.mp3',
        audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/002255.mp3',
        surahName: 'سورة البقرة',
        surahNumber: 2,
        ayahNumber: 255,
        durationSeconds: 25,
        resolution: '720p HD',
        fileSizeBytes: 828000, // 828 KB فيديو 720p MP4
        initialLikesCount: 5410,
        tags: ['آية_الكرسي', 'حفظ', 'أعظم_آية'],
        gradientColors: [Color(0xFF134E5E), Color(0xFF71B280)],
        tafsirOrExplanation: 'تشتمل على عشر جمل مستقلة كل منها تدل على صفة من صفات الكمال لله جل وعلا.',
      ),
      ReelItem(
        id: 'wamda_06',
        title: 'نداء الرحمة الإلهية',
        contentSnippet: '﴿قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ﴾',
        category: ReelCategory.dawah,
        authorName: 'محمد صديق المنشاوي',
        videoPath: 'assets/wamadat/wamda_06.mp4',
        assetPath: 'assets/wamadat/wamda_06.mp3',
        audioUrl: 'https://everyayah.com/data/Minshawy_Murattal_128kbps/039053.mp3',
        surahName: 'سورة الزمر',
        surahNumber: 39,
        ayahNumber: 53,
        durationSeconds: 20,
        resolution: '720p HD',
        fileSizeBytes: 981000, // 981 KB فيديو 720p MP4
        initialLikesCount: 4200,
        tags: ['توبة', 'رحمة_الله', 'موعظة'],
        gradientColors: [Color(0xFF2E0854), Color(0xFF6B117A)],
        tafsirOrExplanation: 'أرجى آية في كتاب الله تدعو كل مقصر ومذنب إلى المبادرة بالتوبة والاستغفار.',
      ),
      ReelItem(
        id: 'wamda_07',
        title: 'مطلع سورة الرحمن',
        contentSnippet: '﴿الرَّحْمَٰنُ ۝ عَلَّمَ الْقُرْآنَ ۝ خَلَقَ الْإِنسَانَ ۝ عَلَّمَهُ الْبَيَانَ﴾',
        category: ReelCategory.quran,
        authorName: 'محمود خليل الحصري',
        videoPath: 'assets/wamadat/wamda_07.mp4',
        assetPath: 'assets/wamadat/wamda_07.mp3',
        audioUrl: 'https://everyayah.com/data/Husary_128kbps/055001.mp3',
        surahName: 'سورة الرحمن',
        surahNumber: 55,
        ayahNumber: 1,
        durationSeconds: 9,
        resolution: '720p HD',
        fileSizeBytes: 339000, // 339 KB فيديو 720p MP4
        initialLikesCount: 3890,
        tags: ['سورة_الرحمن', 'تلاوة_خاشعة', 'قرآن'],
        gradientColors: [Color(0xFF1E3C72), Color(0xFF2A5298)],
        tafsirOrExplanation: 'افتتاح باسم الرحمن لبيان عظيم نعمه، وأجلها تعليم القرآن وبيان اللسان.',
      ),
      ReelItem(
        id: 'wamda_08',
        title: 'سورة الضحى - بشرى ولطف',
        contentSnippet: '﴿مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ ۝ وَلَلْآخِرَةُ خَيْرٌ لَّكَ مِنَ الْأُولَىٰ ۝ وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ﴾',
        category: ReelCategory.dawah,
        authorName: 'مشاري راشد العفاسي',
        videoPath: 'assets/wamadat/wamda_08.mp4',
        assetPath: 'assets/wamadat/wamda_08.mp3',
        audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/093003.mp3',
        surahName: 'سورة الضحى',
        surahNumber: 93,
        ayahNumber: 3,
        durationSeconds: 10,
        resolution: '720p HD',
        fileSizeBytes: 447000, // 447 KB فيديو 720p MP4
        initialLikesCount: 4620,
        tags: ['الضحى', 'بشرى', 'سلوة_المحزون'],
        gradientColors: [Color(0xFF4A154B), Color(0xFF0F141C)],
        tafsirOrExplanation: 'تسلية وتطمين لقلب النبي صلى الله عليه وسلم، ولكل مؤمن أصابه غم أو فتور.',
      ),
    ];
  }
}
